/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.vectorsearch.faiss.swig;

public class FastScanStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FastScanStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FastScanStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_FastScanStats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setT0(long value) {
    swigfaissJNI.FastScanStats_t0_set(swigCPtr, this, value);
  }

  public long getT0() {
    return swigfaissJNI.FastScanStats_t0_get(swigCPtr, this);
  }

  public void setT1(long value) {
    swigfaissJNI.FastScanStats_t1_set(swigCPtr, this, value);
  }

  public long getT1() {
    return swigfaissJNI.FastScanStats_t1_get(swigCPtr, this);
  }

  public void setT2(long value) {
    swigfaissJNI.FastScanStats_t2_set(swigCPtr, this, value);
  }

  public long getT2() {
    return swigfaissJNI.FastScanStats_t2_get(swigCPtr, this);
  }

  public void setT3(long value) {
    swigfaissJNI.FastScanStats_t3_set(swigCPtr, this, value);
  }

  public long getT3() {
    return swigfaissJNI.FastScanStats_t3_get(swigCPtr, this);
  }

  public FastScanStats() {
    this(swigfaissJNI.new_FastScanStats(), true);
  }

  public void reset() {
    swigfaissJNI.FastScanStats_reset(swigCPtr, this);
  }

}
