/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.vectorsearch.faiss.swig;

public class IndexPQFastScan extends Index {
  private transient long swigCPtr;

  protected IndexPQFastScan(long cPtr, boolean cMemoryOwn) {
    super(swigfaissJNI.IndexPQFastScan_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexPQFastScan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_IndexPQFastScan(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setPq(ProductQuantizer value) {
    swigfaissJNI.IndexPQFastScan_pq_set(swigCPtr, this, ProductQuantizer.getCPtr(value), value);
  }

  public ProductQuantizer getPq() {
    long cPtr = swigfaissJNI.IndexPQFastScan_pq_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ProductQuantizer(cPtr, false);
  }

  public void setImplem(int value) {
    swigfaissJNI.IndexPQFastScan_implem_set(swigCPtr, this, value);
  }

  public int getImplem() {
    return swigfaissJNI.IndexPQFastScan_implem_get(swigCPtr, this);
  }

  public void setSkip(int value) {
    swigfaissJNI.IndexPQFastScan_skip_set(swigCPtr, this, value);
  }

  public int getSkip() {
    return swigfaissJNI.IndexPQFastScan_skip_get(swigCPtr, this);
  }

  public void setBbs(int value) {
    swigfaissJNI.IndexPQFastScan_bbs_set(swigCPtr, this, value);
  }

  public int getBbs() {
    return swigfaissJNI.IndexPQFastScan_bbs_get(swigCPtr, this);
  }

  public void setQbs(int value) {
    swigfaissJNI.IndexPQFastScan_qbs_set(swigCPtr, this, value);
  }

  public int getQbs() {
    return swigfaissJNI.IndexPQFastScan_qbs_get(swigCPtr, this);
  }

  public void setNtotal2(long value) {
    swigfaissJNI.IndexPQFastScan_ntotal2_set(swigCPtr, this, value);
  }

  public long getNtotal2() {
    return swigfaissJNI.IndexPQFastScan_ntotal2_get(swigCPtr, this);
  }

  public void setM2(long value) {
    swigfaissJNI.IndexPQFastScan_M2_set(swigCPtr, this, value);
  }

  public long getM2() {
    return swigfaissJNI.IndexPQFastScan_M2_get(swigCPtr, this);
  }

  public void setCodes(AlignedTableUint8 value) {
    swigfaissJNI.IndexPQFastScan_codes_set(swigCPtr, this, AlignedTableUint8.getCPtr(value), value);
  }

  public AlignedTableUint8 getCodes() {
    long cPtr = swigfaissJNI.IndexPQFastScan_codes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AlignedTableUint8(cPtr, false);
  }

  public void setOrig_codes(SWIGTYPE_p_unsigned_char value) {
    swigfaissJNI.IndexPQFastScan_orig_codes_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getOrig_codes() {
    long cPtr = swigfaissJNI.IndexPQFastScan_orig_codes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public IndexPQFastScan(int d, long M, long nbits, MetricType metric, int bbs) {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_0(d, M, nbits, metric.swigValue(), bbs), true);
  }

  public IndexPQFastScan(int d, long M, long nbits, MetricType metric) {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_1(d, M, nbits, metric.swigValue()), true);
  }

  public IndexPQFastScan(int d, long M, long nbits) {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_2(d, M, nbits), true);
  }

  public IndexPQFastScan() {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_3(), true);
  }

  public IndexPQFastScan(IndexPQ orig, int bbs) {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_4(IndexPQ.getCPtr(orig), orig, bbs), true);
  }

  public IndexPQFastScan(IndexPQ orig) {
    this(swigfaissJNI.new_IndexPQFastScan__SWIG_5(IndexPQ.getCPtr(orig), orig), true);
  }

  public void train(long n, SWIGTYPE_p_float x) {
    swigfaissJNI.IndexPQFastScan_train(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x));
  }

  public void add(long n, SWIGTYPE_p_float x) {
    swigfaissJNI.IndexPQFastScan_add(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x));
  }

  public void reset() {
    swigfaissJNI.IndexPQFastScan_reset(swigCPtr, this);
  }

  public void search(long n, SWIGTYPE_p_float x, long k, SWIGTYPE_p_float distances, SWIGTYPE_p_long labels) {
    swigfaissJNI.IndexPQFastScan_search(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), k, SWIGTYPE_p_float.getCPtr(distances), SWIGTYPE_p_long.getCPtr(labels));
  }

  public void compute_quantized_LUT(long n, SWIGTYPE_p_float x, SWIGTYPE_p_unsigned_char lut, SWIGTYPE_p_float normalizers) {
    swigfaissJNI.IndexPQFastScan_compute_quantized_LUT(swigCPtr, this, n, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_unsigned_char.getCPtr(lut), SWIGTYPE_p_float.getCPtr(normalizers));
  }

}
