/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.vectorsearch.faiss.swig;

public class InvertedListsIOHook {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InvertedListsIOHook(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InvertedListsIOHook obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_InvertedListsIOHook(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getKey() {
    return swigfaissJNI.InvertedListsIOHook_key_get(swigCPtr, this);
  }

  public String getClassname() {
    return swigfaissJNI.InvertedListsIOHook_classname_get(swigCPtr, this);
  }

  public void write(InvertedLists ils, IOWriter f) {
    swigfaissJNI.InvertedListsIOHook_write(swigCPtr, this, InvertedLists.getCPtr(ils), ils, IOWriter.getCPtr(f), f);
  }

  public InvertedLists read(IOReader f, int io_flags) {
    long cPtr = swigfaissJNI.InvertedListsIOHook_read(swigCPtr, this, IOReader.getCPtr(f), f, io_flags);
    return (cPtr == 0) ? null : new InvertedLists(cPtr, false);
  }

  public InvertedLists read_ArrayInvertedLists(IOReader f, int io_flags, long nlist, long code_size, LongVector sizes) {
    long cPtr = swigfaissJNI.InvertedListsIOHook_read_ArrayInvertedLists(swigCPtr, this, IOReader.getCPtr(f), f, io_flags, nlist, code_size, LongVector.getCPtr(sizes), sizes);
    return (cPtr == 0) ? null : new InvertedLists(cPtr, false);
  }

  public static void add_callback(InvertedListsIOHook arg0) {
    swigfaissJNI.InvertedListsIOHook_add_callback(InvertedListsIOHook.getCPtr(arg0), arg0);
  }

  public static void print_callbacks() {
    swigfaissJNI.InvertedListsIOHook_print_callbacks();
  }

  public static InvertedListsIOHook lookup(int h) {
    long cPtr = swigfaissJNI.InvertedListsIOHook_lookup(h);
    return (cPtr == 0) ? null : new InvertedListsIOHook(cPtr, false);
  }

  public static InvertedListsIOHook lookup_classname(String classname) {
    long cPtr = swigfaissJNI.InvertedListsIOHook_lookup_classname(classname);
    return (cPtr == 0) ? null : new InvertedListsIOHook(cPtr, false);
  }

}
