/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.vectorsearch.faiss.swig;

public class IVFFastScanStats {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IVFFastScanStats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IVFFastScanStats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_IVFFastScanStats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimes(long[] value) {
    swigfaissJNI.IVFFastScanStats_times_set(swigCPtr, this, value);
  }

  public long[] getTimes() {
    return swigfaissJNI.IVFFastScanStats_times_get(swigCPtr, this);
  }

  public void setT_compute_distance_tables(long value) {
    swigfaissJNI.IVFFastScanStats_t_compute_distance_tables_set(swigCPtr, this, value);
  }

  public long getT_compute_distance_tables() {
    return swigfaissJNI.IVFFastScanStats_t_compute_distance_tables_get(swigCPtr, this);
  }

  public void setT_round(long value) {
    swigfaissJNI.IVFFastScanStats_t_round_set(swigCPtr, this, value);
  }

  public long getT_round() {
    return swigfaissJNI.IVFFastScanStats_t_round_get(swigCPtr, this);
  }

  public void setT_copy_pack(long value) {
    swigfaissJNI.IVFFastScanStats_t_copy_pack_set(swigCPtr, this, value);
  }

  public long getT_copy_pack() {
    return swigfaissJNI.IVFFastScanStats_t_copy_pack_get(swigCPtr, this);
  }

  public void setT_scan(long value) {
    swigfaissJNI.IVFFastScanStats_t_scan_set(swigCPtr, this, value);
  }

  public long getT_scan() {
    return swigfaissJNI.IVFFastScanStats_t_scan_get(swigCPtr, this);
  }

  public void setT_to_flat(long value) {
    swigfaissJNI.IVFFastScanStats_t_to_flat_set(swigCPtr, this, value);
  }

  public long getT_to_flat() {
    return swigfaissJNI.IVFFastScanStats_t_to_flat_get(swigCPtr, this);
  }

  public void setReservoir_times(long[] value) {
    swigfaissJNI.IVFFastScanStats_reservoir_times_set(swigCPtr, this, value);
  }

  public long[] getReservoir_times() {
    return swigfaissJNI.IVFFastScanStats_reservoir_times_get(swigCPtr, this);
  }

  public double Mcy_at(int i) {
    return swigfaissJNI.IVFFastScanStats_Mcy_at(swigCPtr, this, i);
  }

  public double Mcy_reservoir_at(int i) {
    return swigfaissJNI.IVFFastScanStats_Mcy_reservoir_at(swigCPtr, this, i);
  }

  public IVFFastScanStats() {
    this(swigfaissJNI.new_IVFFastScanStats(), true);
  }

  public void reset() {
    swigfaissJNI.IVFFastScanStats_reset(swigCPtr, this);
  }

}
