/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.vectorsearch.faiss.swig;

public class OnDiskOneListVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnDiskOneListVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnDiskOneListVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_OnDiskOneListVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OnDiskOneListVector() {
    this(swigfaissJNI.new_OnDiskOneListVector(), true);
  }

  public void push_back(OnDiskOneList arg0) {
    swigfaissJNI.OnDiskOneListVector_push_back(swigCPtr, this, OnDiskOneList.getCPtr(arg0), arg0);
  }

  public void clear() {
    swigfaissJNI.OnDiskOneListVector_clear(swigCPtr, this);
  }

  public OnDiskOneList data() {
    long cPtr = swigfaissJNI.OnDiskOneListVector_data(swigCPtr, this);
    return (cPtr == 0) ? null : new OnDiskOneList(cPtr, false);
  }

  public long size() {
    return swigfaissJNI.OnDiskOneListVector_size(swigCPtr, this);
  }

  public OnDiskOneList at(long n) {
    return new OnDiskOneList(swigfaissJNI.OnDiskOneListVector_at(swigCPtr, this, n), true);
  }

  public void resize(long n) {
    swigfaissJNI.OnDiskOneListVector_resize(swigCPtr, this, n);
  }

  public void swap(OnDiskOneListVector other) {
    swigfaissJNI.OnDiskOneListVector_swap(swigCPtr, this, OnDiskOneListVector.getCPtr(other), other);
  }

}
